### ISSUE TITLE
AppToken?

### ISSUE THREAD

**Issue by jooles** [trummerjo/pvr.zattoo#2]
Hey :)

Das appToken scheint nicht mehr geladen zu werden.
Finde auch im Quelltext der Seite keine entsprechende Referenz mehr.

Die scheinen etwas geändert zu haben, oder?
Hast du hierfür schon einen fix?

VG

**Comment by trummerjo** [comment]
`curl -s zattoo.com | grep appToken.*\'.*\'`

Funktioniert noch.

**Comment by jooles** [comment]
Hmm.. dann mach ich irgendwas anders:

> $ curl -s zattoo.com | grep appToken._\'._\'
> zsh: no matches found: appToken._'._'

noch irgendeine idee?

**Comment by trummerjo** [comment]
`curl -s zattoo.com`

schau selbst nach im Quelltext.
Im Browser ist das Token nicht zu finden.

**Comment by jooles** [comment]
Huch, stimmt. Danke!
Komisch, erhielt nämlich immer fehler beim Login.

(Baue gerade ein bisschen was mittels nodejs nach). Aber danke, dann forsche ich mal weiter :)
